---
- hosts: ios
  gather_facts: false
  connection: local

  vars:
    cli:
      username: "vagrant"
      password: "vagrant"

  tasks:

    ################################################################
    # Run tests first - any issues we exit the play
    ################################################################    
    # This was a massive learning curve on how to degregister results
    # when you are looping through a set of host vars
    - name: run first check on {{inventory_hostname}}
      ios_command:
        commands: "{{ hostvars[item]['command'] }}"
        provider: "{{ cli }}"
      
      with_items: "{{ groups['ios'] }}"
      register: show

    - set_fact:
        test1: "{{ hostvars[item]['description'] }}"
      with_items: "{{ groups['ios'] }}"

      tags:
        - show


    # This is a test to run the meta handler to close playbook
    # if the result it true then we need to exit gracefully
    - name: debug the check and exit the playbook if necessary
      debug:
        msg: "We have a match: {{item.stdout}} "
        # var: "{{show.stdout}}"
        # var: "{{item.stdout_lines}}"

      with_items: "{{ show.results }}"
      when: 
        - '"{{test1}}" in "{{item.stdout_lines}}"' 
        # // this works!!!
        # - '"Hello World" not in show.results'
        

    ################################################################
    # Push the config here
    ################################################################   
    # Need to work out how to loop over the lines in the host vars.
    # As we need to be able to supply a list with a parent.
    # Else we just do line1, line2 etc, which might be easier

    # - name: set a description
    #   when: result.find('World') != -1

    #   ios_config:
    #     provider: "{{ cli }}"
    #     lines:
    #       - "{{ hostvars[item]['description'] }}"

    #     parents: "{{ hostvars[item]['interface'] }}"
    #     save_when: modified


    #   register: "set_interface"

    #   with_items: "{{ groups['ios'] }}"
    #   tags:
    #     - description

    ################################################################
    # backup the config here
    ################################################################ 


