---
- hosts: oneshot
  gather_facts: false
  connection: local

  vars:
    run_tests: "yes"

    filename: "commands.csv"
    csvfile: "{{ lookup('file', '{{filename}}') }}"
    scr: "./commands.j2"
    dst: "./hosts"

    cli:
      username: "vagrant"
      password: "vagrant"
      host: "{{ ansible_ssh_host }}"
    
    tests:
      inventory: "show inventory | i SN"
      version: "show version | i Version"
      hostname: "show run | i hostname"
      
  tasks:
    # ----
    # TODO
    # ----
    # Make sure not to overwrite other config
    # Taken from extra vars, not run everytime
    # Add a debug option, again from extra vars and add to all debugs
    # Add tags to all tasks
    # Add option to backup before a change (backup role)
    # Add option to backup after a change
    # Make it NXOS or IOS/XE agnostic 
    # Turn into a role at this point
        # supply path to the csv
        # again with option to generate the file or not

    ################################################################
    # Static parse of csv file to YAML host inventory
    ################################################################ 

    - name: Parse CSV To YAML
      template:
        src: "{{scr}}"
        dest: "{{dst}}"
      run_once: true

    ################################################################
    # Run tests first - any issues we exit the play
    ################################################################ 
    
    - name: Gather some custom facts {{ inventory_hostname }} {{ ansible_ssh_host}}
      ios_command:
        commands: 
          - "{{tests['inventory']}}"
          - "{{tests['version']}}"
          - "{{tests['hostname']}}"

        provider: "{{ cli }}"
      register: run_tests
      when: ("yes" in run_tests)

    - name: Print the tests 
      debug:
        var: run_tests
      when: run_tests is defined 
    
    # ################################################################
    # # Set the results of the above actions, to test with meta handlers
    # ################################################################

    - name: Check results of the tests in one task
      set_fact: 
        test_combo_result: "1"

      when: ("serno in item" and "type in item" and "inventory_hostname in item")
      with_items: "{{run_tests.stdout}}"

    # ################################################################
    # # More debugging
    # ################################################################

    - name: debug 
      debug:
        var: test_combo_result
 
    # ################################################################
    # # At this point we can stack up the exit conditions with the logic
    # # in the When statement
    # # Turns out the module is idempotent, when you make it all case 
    # # sensitive!!
    # # So can make more host tests and still end with meta, just not
    # # the config
    # ################################################################

    - meta: end_play
      when: (test_combo_result is not defined)

    # ################################################################
    # # Attempt to push the config here
    # ################################################################   

    - name: Push a set of commands
      ios_config:
        provider: "{{ cli }}"
        lines:
          - "{{ hostvars[item]['line1'] }}"
          - "{{ hostvars[item]['line2'] }}"

        parents: "{{ hostvars[item]['parent'] }}"
        save_when: modified

      register: "set_config"

      with_items: "{{ groups['oneshot'] }}"
      tags:
        - description

    # ################################################################
    # # Push the config here
    # ################################################################  

    - name: debug
      debug:
        var: set_config

    # # # ################################################################
    # # # # backup the config here
    # # # ################################################################ 


